[profile.default]
src = "src"
out = "artifacts"
libs = [
    "lib",
    "node_modules",
]
fs_permissions = [{ access = "read", path = "../"}]

solc_version = '0.8.26'
evm_version = 'cancun'
ffi = true
via_ir = true

uni = "${UNI_RPC_URL}"